### ISSUE TITLE
Looking for WholeBrain connectivity matrix that includes all nodes

### ISSUE THREAD

**Issue by kimberlylray** [dPys/PyNets#148]
I ran PyNets on each of my subjects separately using the Schaefer2018_400Parcels_7Networks_order_FSLMNI152_2mm atlas. 
While there are 400 nodes in this atlas, it looks like 5 or so nodes were outside of my brain mask and not included in the analysis. This is great, however, now when I look at the estimate files, they are 398x398 for one subject and 397x397 for another, etc.  
Is there a whole brain output somewhere that includes all 400 nodes (I would suppose that the pruned nodes outside of the mask would simply have zeros in their corresponding row/column)?  this would be beneficial so that I can generate a group graph. 

Thanks

**Comment by dPys** [comment]
Hi @kimberlylray , 
Just saw this and sorry for the delayed reply! If you are indeed still wanting to use the brain masks to prune nodes outside of the brain, then no matter what those nodes will be omitted from the graph and you will inevitably get some resulting graphs with different dimensions.

The easiest thing to do might be to just pad the arrays with zeroes along the missing edges to achieve the target dimensions of the graph (i.e. 400 x 400):

So if your array is called conn_mat, it would be something like:
```
import numpy as np
conn_matrix = np.load('/path/to/mat.npy')
conn_matrix_padded = np.zeros((400, 400))
conn_matrix_padded[:conn_matrix.shape[0],:conn_matrix.shape[1]] = conn_matrix
```

Let me know if that helps!
@dPys

**Comment by kimberlylray** [comment]
HEy @dPys ,
I'd like to keep the node ordering across participants consistent so that I can accurately create a group mean or group graph. So by adding zeros at the end of the matrix, the order of ROIs in the FC matrix is not the same across participants. 
Is there a record of which ROIs get excluded? 
Thanks again!

**Comment by dPys** [comment]
Hi @kimberlylray ,

Before extracting the time-series from the nodes but after the masking? no such record of omitted nodes is kept to save on disk space, but I could consider adding this in as a verbose option. As a side-note, the files generated that end in *unthresh_mat.npy can also be useful because these are the raw graphs without any thresholding applied (or pruning in the case of graph fragmentation).

One way that you might be able to backtrack to figure out which nodes/edges are missing is to check out the labelnames.pkl files which contain the indices of the nodes that were ultimately included from the atlas. 

You can load this file into python as a list like so:
```
import pickle
with open('atlas_labelnames_002_mask.pkl', 'rb') as f:
    labels = pickle.load(f)
```
You may even be able to combine that code snippet with the zero-padding approach from the earlier post to insert padding only for those rows/columns correspond to nodes whose index is not found in 'labels'? I'm guessing that would be better than having to re-run the complete workflow across subjects (i.e. without brain-masks included)...

@dPys
